// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Announcement represents a Canvas announcement (a discussion topic with
 * is_announcement=true).  It is returned by the discussion_topics API.
 */
export class Announcement {
    /**
     * Creates a new Announcement instance.
     * @param {Partial<Announcement>} [$$source = {}] - The source object to create the Announcement.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * Message is the HTML body of the announcement.
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("posted_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["posted_at"] = "";
        }
        if (!("delayed_post_at" in $$source)) {
            /**
             * DelayedPostAt is set when the announcement is scheduled for future posting.
             * @member
             * @type {string | null}
             */
            this["delayed_post_at"] = null;
        }
        if (!("author" in $$source)) {
            /**
             * Author identifies who posted the announcement.
             * @member
             * @type {AnnouncementAuthor}
             */
            this["author"] = (new AnnouncementAuthor());
        }
        if (!("read_state" in $$source)) {
            /**
             * ReadState is "read" or "unread" for the current user.
             * @member
             * @type {string}
             */
            this["read_state"] = "";
        }
        if (!("discussion_subentry_count" in $$source)) {
            /**
             * DiscussionSubentryCount is the number of replies.
             * @member
             * @type {number}
             */
            this["discussion_subentry_count"] = 0;
        }
        if (!("url" in $$source)) {
            /**
             * URL is the Canvas web URL for the announcement.
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Announcement instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Announcement}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField5_0($$parsedSource["author"]);
        }
        return new Announcement(/** @type {Partial<Announcement>} */($$parsedSource));
    }
}

/**
 * AnnouncementAuthor identifies who posted an announcement.
 */
export class AnnouncementAuthor {
    /**
     * Creates a new AnnouncementAuthor instance.
     * @param {Partial<AnnouncementAuthor>} [$$source = {}] - The source object to create the AnnouncementAuthor.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnnouncementAuthor instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnnouncementAuthor}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnnouncementAuthor(/** @type {Partial<AnnouncementAuthor>} */($$parsedSource));
    }
}

/**
 * Assignment represents a Canvas assignment.
 */
export class Assignment {
    /**
     * Creates a new Assignment instance.
     * @param {Partial<Assignment>} [$$source = {}] - The source object to create the Assignment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("due_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["due_at"] = null;
        }
        if (!("lock_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["lock_at"] = null;
        }
        if (!("unlock_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["unlock_at"] = null;
        }
        if (!("points_possible" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["points_possible"] = 0;
        }
        if (!("assignment_group_id" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["assignment_group_id"] = null;
        }
        if (!("submission_types" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["submission_types"] = [];
        }
        if (!("allowed_attempts" in $$source)) {
            /**
             * -1 = unlimited
             * @member
             * @type {number | null}
             */
            this["allowed_attempts"] = null;
        }
        if (!("published" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["published"] = false;
        }
        if (!("workflow_state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflow_state"] = "";
        }
        if (!("has_submitted_submissions" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_submitted_submissions"] = false;
        }
        if (!("needs_grading_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["needs_grading_count"] = 0;
        }
        if (!("html_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["html_url"] = "";
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Assignment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Assignment}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("submission_types" in $$parsedSource) {
            $$parsedSource["submission_types"] = $$createField8_0($$parsedSource["submission_types"]);
        }
        return new Assignment(/** @type {Partial<Assignment>} */($$parsedSource));
    }
}

/**
 * AssignmentGroup represents a Canvas assignment group (weighting category).
 */
export class AssignmentGroup {
    /**
     * Creates a new AssignmentGroup instance.
     * @param {Partial<AssignmentGroup>} [$$source = {}] - The source object to create the AssignmentGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssignmentGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssignmentGroup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssignmentGroup(/** @type {Partial<AssignmentGroup>} */($$parsedSource));
    }
}

/**
 * Attachment represents a file attached to a submission.
 */
export class Attachment {
    /**
     * Creates a new Attachment instance.
     * @param {Partial<Attachment>} [$$source = {}] - The source object to create the Attachment.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("display_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display_name"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("content-type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content-type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attachment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Attachment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attachment(/** @type {Partial<Attachment>} */($$parsedSource));
    }
}

/**
 * Course represents a Canvas course.
 */
export class Course {
    /**
     * Creates a new Course instance.
     * @param {Partial<Course>} [$$source = {}] - The source object to create the Course.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("course_code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["course_code"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CourseTerm | null | undefined}
             */
            this["term"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Course instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Course}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("term" in $$parsedSource) {
            $$parsedSource["term"] = $$createField3_0($$parsedSource["term"]);
        }
        return new Course(/** @type {Partial<Course>} */($$parsedSource));
    }
}

/**
 * CourseItem merges assignments and quizzes for the frontend course view.
 */
export class CourseItem {
    /**
     * Creates a new CourseItem instance.
     * @param {Partial<CourseItem>} [$$source = {}] - The source object to create the CourseItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "assignment" or "quiz"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("due_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["due_at"] = null;
        }
        if (!("points" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["points"] = 0;
        }
        if (!("published" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["published"] = false;
        }
        if (!("needs_grading_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["needs_grading_count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["quiz_type"] = undefined;
        }
        if (!("assignment_id" in $$source)) {
            /**
             * for quizzes: the linked Canvas assignment ID for grade upload
             * @member
             * @type {number}
             */
            this["assignment_id"] = 0;
        }
        if (!("is_old_quiz" in $$source)) {
            /**
             * true if this is an old-style Canvas quiz with downloadable questions
             * @member
             * @type {boolean}
             */
            this["is_old_quiz"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CourseItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CourseItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CourseItem(/** @type {Partial<CourseItem>} */($$parsedSource));
    }
}

/**
 * CourseStats holds computed statistics for the Info tab.
 */
export class CourseStats {
    /**
     * Creates a new CourseStats instance.
     * @param {Partial<CourseStats>} [$$source = {}] - The source object to create the CourseStats.
     */
    constructor($$source = {}) {
        if (!("student_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["student_count"] = 0;
        }
        if (!("total_items" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_items"] = 0;
        }
        if (!("published_items" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["published_items"] = 0;
        }
        if (!("needs_grading" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["needs_grading"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CourseStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CourseStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CourseStats(/** @type {Partial<CourseStats>} */($$parsedSource));
    }
}

/**
 * CourseTerm represents the nested term object in a Course.
 */
export class CourseTerm {
    /**
     * Creates a new CourseTerm instance.
     * @param {Partial<CourseTerm>} [$$source = {}] - The source object to create the CourseTerm.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CourseTerm instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CourseTerm}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CourseTerm(/** @type {Partial<CourseTerm>} */($$parsedSource));
    }
}

/**
 * FileInfo is the enriched file metadata stored after a successful upload.
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("public_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["public_url"] = "";
        }
        if (!("folder_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * Submission represents a student submission for an assignment.
 */
export class Submission {
    /**
     * Creates a new Submission instance.
     * @param {Partial<Submission>} [$$source = {}] - The source object to create the Submission.
     */
    constructor($$source = {}) {
        if (!("assignment_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["assignment_id"] = 0;
        }
        if (!("user_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["user_id"] = 0;
        }
        if (!("score" in $$source)) {
            /**
             * float64 or null
             * @member
             * @type {any}
             */
            this["score"] = null;
        }
        if (!("submitted_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["submitted_at"] = null;
        }
        if (!("workflow_state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workflow_state"] = "";
        }
        if (!("late" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["late"] = false;
        }
        if (!("grade" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["grade"] = null;
        }
        if (!("graded_at" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["graded_at"] = null;
        }
        if (!("grader_id" in $$source)) {
            /**
             * @member
             * @type {number | null}
             */
            this["grader_id"] = null;
        }
        if (!("missing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["missing"] = false;
        }
        if (!("excused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["excused"] = false;
        }
        if (!("submission_type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["submission_type"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("preview_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preview_url"] = "";
        }
        if (!("attempt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempt"] = 0;
        }
        if (!("attachments" in $$source)) {
            /**
             * @member
             * @type {Attachment[]}
             */
            this["attachments"] = [];
        }
        if (!("submission_history" in $$source)) {
            /**
             * @member
             * @type {SubmissionHistoryItem[]}
             */
            this["submission_history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Submission instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Submission}
     */
    static createFrom($$source = {}) {
        const $$createField16_0 = $$createType5;
        const $$createField17_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField16_0($$parsedSource["attachments"]);
        }
        if ("submission_history" in $$parsedSource) {
            $$parsedSource["submission_history"] = $$createField17_0($$parsedSource["submission_history"]);
        }
        return new Submission(/** @type {Partial<Submission>} */($$parsedSource));
    }
}

/**
 * SubmissionDataItem holds one question answer from a quiz submission.
 */
export class SubmissionDataItem {
    /**
     * Creates a new SubmissionDataItem instance.
     * @param {Partial<SubmissionDataItem>} [$$source = {}] - The source object to create the SubmissionDataItem.
     */
    constructor($$source = {}) {
        if (!("question_id" in $$source)) {
            /**
             * int or string from Canvas
             * @member
             * @type {any}
             */
            this["question_id"] = null;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("points" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["points"] = 0;
        }
        if (!("correct" in $$source)) {
            /**
             * string: "correct", "incorrect", "undefined"
             * @member
             * @type {any}
             */
            this["correct"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmissionDataItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubmissionDataItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubmissionDataItem(/** @type {Partial<SubmissionDataItem>} */($$parsedSource));
    }
}

/**
 * SubmissionHistoryItem represents one entry in a submission's history.
 */
export class SubmissionHistoryItem {
    /**
     * Creates a new SubmissionHistoryItem instance.
     * @param {Partial<SubmissionHistoryItem>} [$$source = {}] - The source object to create the SubmissionHistoryItem.
     */
    constructor($$source = {}) {
        if (!("attachments" in $$source)) {
            /**
             * @member
             * @type {Attachment[]}
             */
            this["attachments"] = [];
        }
        if (!("submission_data" in $$source)) {
            /**
             * @member
             * @type {SubmissionDataItem[]}
             */
            this["submission_data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubmissionHistoryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SubmissionHistoryItem}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField0_0($$parsedSource["attachments"]);
        }
        if ("submission_data" in $$parsedSource) {
            $$parsedSource["submission_data"] = $$createField1_0($$parsedSource["submission_data"]);
        }
        return new SubmissionHistoryItem(/** @type {Partial<SubmissionHistoryItem>} */($$parsedSource));
    }
}

/**
 * User represents a Canvas user (typically a student in the context of a course).
 */
export class User {
    /**
     * Creates a new User instance.
     * @param {Partial<User>} [$$source = {}] - The source object to create the User.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("sis_user_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sis_user_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {User}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User(/** @type {Partial<User>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AnnouncementAuthor.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = CourseTerm.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = Attachment.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SubmissionHistoryItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = SubmissionDataItem.createFrom;
const $$createType9 = $Create.Array($$createType8);
