// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App holds application state and exposes methods to the Svelte frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function BrowseCSVFile() {
    return $Call.ByID(1665836591);
}

/**
 * BrowseDirectory opens a native OS directory picker and returns the selected path.
 * @returns {$CancellablePromise<string>}
 */
export function BrowseDirectory() {
    return $Call.ByID(320967638);
}

/**
 * CancelUpload cancels a running grade upload.
 * @returns {$CancellablePromise<void>}
 */
export function CancelUpload() {
    return $Call.ByID(409390550);
}

/**
 * ConvertMarkdown converts a Markdown file to PDF. Returns the output path.
 * @param {string} inputPath
 * @param {string} outputPath
 * @returns {$CancellablePromise<void>}
 */
export function ConvertMarkdown(inputPath, outputPath) {
    return $Call.ByID(3052073377, inputPath, outputPath);
}

/**
 * CreateAnnouncement creates a new announcement in a course.
 * @param {number} courseID
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function CreateAnnouncement(courseID, title, message) {
    return $Call.ByID(2335980410, courseID, title, message);
}

/**
 * CreateAssignment creates a new assignment in a course.
 * @param {number} courseID
 * @param {{ [_ in string]?: any }} data
 * @returns {$CancellablePromise<models$0.Assignment | null>}
 */
export function CreateAssignment(courseID, data) {
    return $Call.ByID(682310224, courseID, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateAssignmentGroup creates a new assignment group in a course.
 * @param {number} courseID
 * @param {string} name
 * @returns {$CancellablePromise<models$0.AssignmentGroup | null>}
 */
export function CreateAssignmentGroup(courseID, name) {
    return $Call.ByID(2786084883, courseID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeleteAnnouncement deletes an announcement from a course.
 * @param {number} courseID
 * @param {number} topicID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAnnouncement(courseID, topicID) {
    return $Call.ByID(3389107673, courseID, topicID);
}

/**
 * DownloadAnnouncementFile downloads a file linked from an announcement.
 * The frontend passes the link text as the suggested filename and the
 * Canvas file URL.  We parse the file ID, get a pre-authenticated download
 * URL from the REST API (the web URL requires a session cookie), then
 * download the raw bytes.
 * @param {string} fileURL
 * @param {string} suggestedName
 * @returns {$CancellablePromise<void>}
 */
export function DownloadAnnouncementFile(fileURL, suggestedName) {
    return $Call.ByID(968913184, fileURL, suggestedName);
}

/**
 * EditAssignment updates an existing assignment in a course.
 * @param {number} courseID
 * @param {number} assignmentID
 * @param {{ [_ in string]?: any }} data
 * @returns {$CancellablePromise<models$0.Assignment | null>}
 */
export function EditAssignment(courseID, assignmentID, data) {
    return $Call.ByID(707614004, courseID, assignmentID, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportAssignmentSubmissions downloads all file attachments for an assignment.
 * dirPath is chosen by the user beforehand via BrowseDirectory.
 * Progress is reported via Wails events: assign-dl:start, assign-dl:progress,
 * assign-dl:done, assign-dl:error.
 * @param {number} courseID
 * @param {number} assignmentID
 * @param {string} dirPath
 * @returns {$CancellablePromise<void>}
 */
export function ExportAssignmentSubmissions(courseID, assignmentID, dirPath) {
    return $Call.ByID(3587082039, courseID, assignmentID, dirPath);
}

/**
 * @param {number} courseID
 * @param {number} quizID
 * @param {string} quizTitle
 * @param {string} format
 * @returns {$CancellablePromise<string>}
 */
export function ExportQuizQuestions(courseID, quizID, quizTitle, format) {
    return $Call.ByID(2803714415, courseID, quizID, quizTitle, format);
}

/**
 * ExportQuizSubmissions downloads all submissions for an old-style quiz.
 * Opens a directory picker, then writes one file per student in the background.
 * Progress is reported via Wails events: submissions:progress, submissions:done, submissions:error.
 * @param {number} courseID
 * @param {number} quizID
 * @param {string} format
 * @returns {$CancellablePromise<void>}
 */
export function ExportQuizSubmissions(courseID, quizID, format) {
    return $Call.ByID(3846480403, courseID, quizID, format);
}

/**
 * ExportScoresCSV opens a save dialog and writes a grades matrix CSV
 * (canvas_id, student_name, one column per assignment/quiz).
 * @param {number} courseID
 * @returns {$CancellablePromise<string>}
 */
export function ExportScoresCSV(courseID) {
    return $Call.ByID(3779408532, courseID);
}

/**
 * ExportStudentsCSV opens a save dialog and writes the student roster as CSV.
 * Returns the path of the saved file, or an empty string if the user cancelled.
 * @param {number} courseID
 * @returns {$CancellablePromise<string>}
 */
export function ExportStudentsCSV(courseID) {
    return $Call.ByID(741839237, courseID);
}

/**
 * GetAnnouncements returns announcements for a course.
 * @param {number} courseID
 * @returns {$CancellablePromise<models$0.Announcement[]>}
 */
export function GetAnnouncements(courseID) {
    return $Call.ByID(4114140397, courseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetAssignmentGroups returns assignment groups for a course.
 * @param {number} courseID
 * @returns {$CancellablePromise<models$0.AssignmentGroup[]>}
 */
export function GetAssignmentGroups(courseID) {
    return $Call.ByID(2057678814, courseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetConfig returns the current app configuration for the frontend.
 * @returns {$CancellablePromise<$models.appConfig | null>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetCourseStats computes aggregate statistics for a course.
 * @param {number} courseID
 * @returns {$CancellablePromise<models$0.CourseStats | null>}
 */
export function GetCourseStats(courseID) {
    return $Call.ByID(1916506057, courseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetCurrentCourse returns the currently selected course, if any.
 * @returns {$CancellablePromise<models$0.Course | null>}
 */
export function GetCurrentCourse() {
    return $Call.ByID(401813317).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetStudentSubmissions returns all submissions for a student across all assignments.
 * @param {number} courseID
 * @param {number} studentID
 * @returns {$CancellablePromise<models$0.Submission[]>}
 */
export function GetStudentSubmissions(courseID, studentID) {
    return $Call.ByID(2518549091, courseID, studentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateCache() {
    return $Call.ByID(3256992434);
}

/**
 * @param {number} courseID
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateCourse(courseID) {
    return $Call.ByID(1873671021, courseID);
}

/**
 * ListAssignments returns assignments for a course.
 * @param {number} courseID
 * @returns {$CancellablePromise<models$0.Assignment[]>}
 */
export function ListAssignments(courseID) {
    return $Call.ByID(2876150117, courseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ListCourseItems returns merged assignments and quizzes for a course.
 * Graded quizzes that also appear as assignments are deduplicated (quiz wins).
 * @param {number} courseID
 * @returns {$CancellablePromise<models$0.CourseItem[]>}
 */
export function ListCourseItems(courseID) {
    return $Call.ByID(1440601512, courseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ListCourses returns all active courses.
 * @returns {$CancellablePromise<models$0.Course[]>}
 */
export function ListCourses() {
    return $Call.ByID(1990119557).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ListStudents returns students enrolled in a course.
 * @param {number} courseID
 * @returns {$CancellablePromise<models$0.User[]>}
 */
export function ListStudents(courseID) {
    return $Call.ByID(2747211197, courseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * ListSubmissions returns submissions for an assignment.
 * @param {number} courseID
 * @param {number} assignmentID
 * @returns {$CancellablePromise<models$0.Submission[]>}
 */
export function ListSubmissions(courseID, assignmentID) {
    return $Call.ByID(37429562, courseID, assignmentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * NeedsSetup returns true when no API token is configured, meaning the
 * frontend should open the settings dialog before attempting any API calls.
 * @returns {$CancellablePromise<boolean>}
 */
export function NeedsSetup() {
    return $Call.ByID(737682639);
}

/**
 * SaveCourseSet persists the course set to config.json.
 * @param {number[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function SaveCourseSet(ids) {
    return $Call.ByID(30801683, ids);
}

/**
 * SaveSettings persists a new Canvas base URL and API token to config.json,
 * then re-initialises the client and cache.  The current course is reset so
 * no stale data from a previous session is shown.
 * @param {string} baseURL
 * @param {string} apiToken
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(baseURL, apiToken) {
    return $Call.ByID(1949631069, baseURL, apiToken);
}

/**
 * SelectCourse sets the active course by ID and returns it.
 * Persists the selection as last_course_id in config.json.
 * @param {number} courseID
 * @returns {$CancellablePromise<models$0.Course | null>}
 */
export function SelectCourse(courseID) {
    return $Call.ByID(2217710872, courseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * TokenFromEnv reports whether the API token is being supplied via the
 * CANVAS_API_TOKEN environment variable (i.e. it cannot be changed from the UI).
 * @returns {$CancellablePromise<boolean>}
 */
export function TokenFromEnv() {
    return $Call.ByID(511663377);
}

/**
 * UpdateAnnouncement updates an existing announcement in a course.
 * @param {number} courseID
 * @param {number} topicID
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAnnouncement(courseID, topicID, title, message) {
    return $Call.ByID(3996813187, courseID, topicID, title, message);
}

/**
 * UploadAnnouncementAttachment opens a file picker, ensures an "Anuncios"
 * folder in the course, uploads the file, and returns its metadata so the
 * frontend can embed a download link in the announcement message.
 * @param {number} courseID
 * @returns {$CancellablePromise<models$0.FileInfo | null>}
 */
export function UploadAnnouncementAttachment(courseID) {
    return $Call.ByID(3606276454, courseID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * UploadGrades runs the full grade upload workflow in the background.
 * Progress is reported via Wails events: upload:status, upload:file_progress,
 * upload:batch_progress, upload:done, upload:error.
 * @param {number} courseID
 * @param {number} assignmentID
 * @param {string} csvPath
 * @returns {$CancellablePromise<void>}
 */
export function UploadGrades(courseID, assignmentID, csvPath) {
    return $Call.ByID(812483064, courseID, assignmentID, csvPath);
}

// Private type creation functions
const $$createType0 = models$0.Assignment.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.AssignmentGroup.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.Announcement.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType2);
const $$createType7 = $models.appConfig.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = models$0.CourseStats.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = models$0.Course.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = models$0.Submission.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($$createType0);
const $$createType16 = models$0.CourseItem.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Array($$createType11);
const $$createType19 = models$0.User.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = models$0.FileInfo.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
