// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * appConfig holds the parsed config.json fields.
 */
export class appConfig {
    /**
     * Creates a new appConfig instance.
     * @param {Partial<appConfig>} [$$source = {}] - The source object to create the appConfig.
     */
    constructor($$source = {}) {
        if (!("canvas_base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["canvas_base_url"] = "";
        }
        if (!("api_token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_token"] = "";
        }
        if (!("last_course_id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_course_id"] = 0;
        }
        if (!("course_set" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["course_set"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new appConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {appConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("course_set" in $$parsedSource) {
            $$parsedSource["course_set"] = $$createField3_0($$parsedSource["course_set"]);
        }
        return new appConfig(/** @type {Partial<appConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
