// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseCSVFile() {
  return window['go']['main']['App']['BrowseCSVFile']();
}

export function BrowseDirectory() {
  return window['go']['main']['App']['BrowseDirectory']();
}

export function CancelUpload() {
  return window['go']['main']['App']['CancelUpload']();
}

export function ConvertMarkdown(arg1, arg2) {
  return window['go']['main']['App']['ConvertMarkdown'](arg1, arg2);
}

export function CreateAnnouncement(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAnnouncement'](arg1, arg2, arg3);
}

export function CreateAssignment(arg1, arg2) {
  return window['go']['main']['App']['CreateAssignment'](arg1, arg2);
}

export function CreateAssignmentGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateAssignmentGroup'](arg1, arg2);
}

export function DeleteAnnouncement(arg1, arg2) {
  return window['go']['main']['App']['DeleteAnnouncement'](arg1, arg2);
}

export function DownloadAnnouncementFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadAnnouncementFile'](arg1, arg2);
}

export function EditAssignment(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditAssignment'](arg1, arg2, arg3);
}

export function ExportAssignmentSubmissions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportAssignmentSubmissions'](arg1, arg2, arg3);
}

export function ExportQuizQuestions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportQuizQuestions'](arg1, arg2, arg3, arg4);
}

export function ExportQuizSubmissions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportQuizSubmissions'](arg1, arg2, arg3);
}

export function ExportScoresCSV(arg1) {
  return window['go']['main']['App']['ExportScoresCSV'](arg1);
}

export function ExportStudentsCSV(arg1) {
  return window['go']['main']['App']['ExportStudentsCSV'](arg1);
}

export function GetAnnouncements(arg1) {
  return window['go']['main']['App']['GetAnnouncements'](arg1);
}

export function GetAssignmentGroups(arg1) {
  return window['go']['main']['App']['GetAssignmentGroups'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCourseStats(arg1) {
  return window['go']['main']['App']['GetCourseStats'](arg1);
}

export function GetCurrentCourse() {
  return window['go']['main']['App']['GetCurrentCourse']();
}

export function GetStudentSubmissions(arg1, arg2) {
  return window['go']['main']['App']['GetStudentSubmissions'](arg1, arg2);
}

export function InvalidateCache() {
  return window['go']['main']['App']['InvalidateCache']();
}

export function InvalidateCourse(arg1) {
  return window['go']['main']['App']['InvalidateCourse'](arg1);
}

export function ListAssignments(arg1) {
  return window['go']['main']['App']['ListAssignments'](arg1);
}

export function ListCourseItems(arg1) {
  return window['go']['main']['App']['ListCourseItems'](arg1);
}

export function ListCourses() {
  return window['go']['main']['App']['ListCourses']();
}

export function ListStudents(arg1) {
  return window['go']['main']['App']['ListStudents'](arg1);
}

export function ListSubmissions(arg1, arg2) {
  return window['go']['main']['App']['ListSubmissions'](arg1, arg2);
}

export function NeedsSetup() {
  return window['go']['main']['App']['NeedsSetup']();
}

export function SaveCourseSet(arg1) {
  return window['go']['main']['App']['SaveCourseSet'](arg1);
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2);
}

export function SelectCourse(arg1) {
  return window['go']['main']['App']['SelectCourse'](arg1);
}

export function TokenFromEnv() {
  return window['go']['main']['App']['TokenFromEnv']();
}

export function UpdateAnnouncement(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateAnnouncement'](arg1, arg2, arg3, arg4);
}

export function UploadAnnouncementAttachment(arg1) {
  return window['go']['main']['App']['UploadAnnouncementAttachment'](arg1);
}

export function UploadGrades(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadGrades'](arg1, arg2, arg3);
}
