// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function BrowseCSVFile():Promise<string>;

export function BrowseDirectory():Promise<string>;

export function CancelUpload():Promise<void>;

export function ConvertMarkdown(arg1:string,arg2:string):Promise<void>;

export function CreateAnnouncement(arg1:number,arg2:string,arg3:string):Promise<void>;

export function CreateAssignment(arg1:number,arg2:Record<string, any>):Promise<models.Assignment>;

export function CreateAssignmentGroup(arg1:number,arg2:string):Promise<models.AssignmentGroup>;

export function DeleteAnnouncement(arg1:number,arg2:number):Promise<void>;

export function DownloadAnnouncementFile(arg1:string,arg2:string):Promise<void>;

export function EditAssignment(arg1:number,arg2:number,arg3:Record<string, any>):Promise<models.Assignment>;

export function ExportAssignmentSubmissions(arg1:number,arg2:number,arg3:string):Promise<void>;

export function ExportQuizQuestions(arg1:number,arg2:number,arg3:string,arg4:string):Promise<string>;

export function ExportQuizSubmissions(arg1:number,arg2:number,arg3:string):Promise<void>;

export function ExportScoresCSV(arg1:number):Promise<string>;

export function ExportStudentsCSV(arg1:number):Promise<string>;

export function GetAnnouncements(arg1:number):Promise<Array<models.Announcement>>;

export function GetAssignmentGroups(arg1:number):Promise<Array<models.AssignmentGroup>>;

export function GetConfig():Promise<main.appConfig>;

export function GetCourseStats(arg1:number):Promise<models.CourseStats>;

export function GetCurrentCourse():Promise<models.Course>;

export function GetStudentSubmissions(arg1:number,arg2:number):Promise<Array<models.Submission>>;

export function InvalidateCache():Promise<void>;

export function InvalidateCourse(arg1:number):Promise<void>;

export function ListAssignments(arg1:number):Promise<Array<models.Assignment>>;

export function ListCourseItems(arg1:number):Promise<Array<models.CourseItem>>;

export function ListCourses():Promise<Array<models.Course>>;

export function ListStudents(arg1:number):Promise<Array<models.User>>;

export function ListSubmissions(arg1:number,arg2:number):Promise<Array<models.Submission>>;

export function NeedsSetup():Promise<boolean>;

export function SaveCourseSet(arg1:Array<number>):Promise<void>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;

export function SelectCourse(arg1:number):Promise<models.Course>;

export function TokenFromEnv():Promise<boolean>;

export function UpdateAnnouncement(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function UploadAnnouncementAttachment(arg1:number):Promise<models.FileInfo>;

export function UploadGrades(arg1:number,arg2:number,arg3:string):Promise<void>;
